Pull request template added
Tractorou24/spark pull request #17
Opened 2023-06-02 19:11 UTC by okaydivyansh

This is a pull request template which was missing and now the issue has been fixed

2023-06-02 20:27 UTC, Tractorou24 requested changes
Thank you for contributing! I requested a small change from you because I'm unable to make it myself since I don't have access to your fork and we can't push modifications to a PR directly...

I have also another small requests:
- Can you move the template file to .github/pull_request_template.md instead of the root directory
- Rename your already created commit (that you will modify to add the modifications) for: `.github: [Enh] Add a pull request template (#5)`

Thank you!

2023-06-02 20:27 UTC, Tractorou24 commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] My code follows the coding style and guidelines of the Spark organization.
`- [ ] My code follows the coding style and guidelines of Spark's already written code .`
We can change this because there is no SPARK organization and no explicitly written style except the written code and resharper profile.

2023-06-02 20:27 UTC, Tractorou24 commented on PULL_REQUEST_TEMPLATE.md
> +Thank you for your contribution to the Spark !
I think `Thank you for your contribution to Spark Engine !` will be better!

2023-06-02 20:52 UTC, okaydivyansh commented
Thank you for your kind review. Requested changes have been made. Thank you.

2023-06-02 20:57 UTC, okaydivyansh commented
#17 I am waiting for the review before this is closed. Thank you!

2023-06-02 21:37 UTC, Tractorou24 commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] My code follows the coding style and guidelines of the Spark organization.
We may want to leave this but just change it to the proposed sentence.

2023-06-02 21:38 UTC, Tractorou24 requested changes
I reopened a comment where we had a misunderstanding.
Also, please squash all the commits to a single one. The message of it is in the last review comment.

If you have any question about how doing it, don't hesitate!

2023-06-03 11:06 UTC, okaydivyansh commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] My code follows the coding style and guidelines of the Spark organization.
I'm really sorry for the misunderstanding but I removed the unwanted sentence. What is the proposed sentence which is mentioned above?

2023-06-03 18:03 UTC, Tractorou24 commented on PULL_REQUEST_TEMPLATE.md
> +- [ ] My code follows the coding style and guidelines of the Spark organization.
`- [ ] My code follows the coding style and guidelines of Spark's already written code. `
it's just changing the coding style and guidelines to the already written code.

2023-06-04 09:16 UTC, Tractorou24 commented
I found I could make modifications to this pr by cloning tour fork, so I made the modifications and I'm merging this now!
Thank you for your contribution!

2023-06-04 09:16 UTC, merged

2023-06-04 09:26 UTC, Tractorou24 reviewed
I found I could make modifications to this pr by cloning tour fork, so I made the modifications and I'm merging this now!
Thank you for your contribution!